let title = "Projekt";
console.log(typeof title);
let screens = "Простые, Сложные, Интерактивные";
console.log(screens.length);
console.log(screens.toLowerCase());
console.log(screens.split(", "));
let screenPrice = 20;
console.log(20);
let rollback = 10;
console.log((50 * 10) / 100);
let fullPrice = 50;
console.log(50);
console.log(typeof fullPrice);
let adaptive;
console.log(typeof adaptive);
